[package]
name = "candle_stink"
version = "0.1.0"
authors = ["mobile-bungalow <lunchette@martys.bathhouse.web>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced_plotters = { path = "../../" }
chrono = "*"
